#!/usr/bin/env python3
"""Synthesises the bundled alert tone and writes it as a data URI module.

The tone this replaced was 17 samples of 8-bit audio at 8 kHz — 2.1 milliseconds, which is a click
rather than a sound. It was audible only at a volume nobody would run a machine at, and the person
who eventually heard it reasonably assumed something was broken elsewhere.

The replacement is a rising three-note figure with a sustained final note: distinctive enough to be
told apart from a system beep, short enough not to be irritating at every escalation, and no more
than a second so it cannot overlap itself when alerts repeat. It is bundled as a data URI so the
application still fetches no audio from anywhere.

    python3 tools/generate-alert-tone.py

Regenerate and the module below is rewritten. This is the source of the sound; the base64 in
`src/infrastructure/browser/alert-tone.ts` is output.
"""

import base64
import math
import struct
from pathlib import Path

SAMPLE_RATE = 16_000  # Nyquist well above the highest harmonic used below.
PEAK = 0.89  # Short of full scale, so no player clips it.

# A major triad, rising. The last note is held: an alert that ends on a sustain reads as a
# statement rather than a stumble, and it survives a device that swallows the first few
# milliseconds of playback.
NOTES = [
    (880.00, 0.13),  # A5
    (1108.73, 0.13),  # C#6
    (1318.51, 0.46),  # E6
]
# A little harmonic content, because a pure sine is both dull and easy to mistake for tinnitus.
HARMONICS = ((1.0, 1.0), (2.0, 0.22), (3.0, 0.08))
ATTACK_SECONDS = 0.006


def render() -> bytes:
    samples: list[float] = []
    for frequency, duration in NOTES:
        count = int(duration * SAMPLE_RATE)
        # Decays to about a tenth of its peak by the end of its slot, so notes overlap slightly
        # and the figure sounds joined rather than chopped.
        decay = duration / 2.3
        for index in range(count):
            t = index / SAMPLE_RATE
            envelope = min(1.0, t / ATTACK_SECONDS) * math.exp(-t / decay)
            value = sum(
                amplitude * math.sin(2 * math.pi * frequency * multiple * t)
                for multiple, amplitude in HARMONICS
            )
            samples.append(value * envelope)

    loudest = max(abs(sample) for sample in samples)
    scale = PEAK / loudest
    return b''.join(
        struct.pack('<h', int(max(-1.0, min(1.0, sample * scale)) * 32_767)) for sample in samples
    )


def wav(pcm: bytes) -> bytes:
    channels, bits = 1, 16
    byte_rate = SAMPLE_RATE * channels * bits // 8
    block_align = channels * bits // 8
    return b''.join(
        [
            b'RIFF',
            struct.pack('<I', 36 + len(pcm)),
            b'WAVEfmt ',
            struct.pack('<IHHIIHH', 16, 1, channels, SAMPLE_RATE, byte_rate, block_align, bits),
            b'data',
            struct.pack('<I', len(pcm)),
            pcm,
        ]
    )


def main() -> None:
    pcm = render()
    audio = wav(pcm)
    encoded = base64.b64encode(audio).decode('ascii')
    seconds = len(pcm) / 2 / SAMPLE_RATE

    lines = [encoded[index : index + 96] for index in range(0, len(encoded), 96)]
    body = '\n'.join(f"  '{line}' +" for line in lines[:-1]) + f"\n  '{lines[-1]}';"

    module = f'''/**
 * The bundled alert tone: a rising three-note figure, {seconds:.2f}s, 16-bit PCM at {SAMPLE_RATE // 1000} kHz.
 *
 * Generated by `tools/generate-alert-tone.py`, which is where the sound is defined — edit that and
 * regenerate rather than hand-editing the base64 below. It is inlined as a data URI so the
 * application fetches no audio from anywhere, which is why the deployment policy needs only
 * `media-src` for `data:` to play it.
 */
export const bundledAlertTone =
{body}

/** How long the bundled tone runs, for interfaces that need to wait it out. */
export const bundledAlertToneSeconds = {seconds:.2f};
'''

    path = Path('src/infrastructure/browser/alert-tone.ts')
    path.write_text(
        module.replace(
            "export const bundledAlertTone =\n",
            "export const bundledAlertTone =\n  'data:audio/wav;base64,' +\n",
        ),
        encoding='utf-8',
    )
    print(f'Wrote {path}: {seconds:.2f}s, {len(audio)} bytes of WAV, {len(encoded)} base64 chars.')


if __name__ == '__main__':
    main()
